#ifndef WORM_CONFIG_H
#define WORM_CONFIG_H

#define SCR_WIDTH 128
#define SCR_HEIGHT 64
#define FB_SIZE (SCR_WIDTH * (SCR_HEIGHT / 8))

#define WORM_START_POSITION_X 51
#define WORM_START_POSITION_Y 36
#define WORM_MOVE_STEP 5
#define WORM_MAX_TRAIL 384
#define WORM_INITIAL_LENGTH 4

#define MAX_APPLES 8
#define APPLE_WIDTH 7
#define APPLE_HEIGHT 7
#define APPLE_LIFE_SECONDS 3
#define APPLE_RESPAWN_SECONDS 2
#define APPLE_RANDOM_TRIES 32

#define BORDER_MARGIN 1
#define BORDER_WIDTH 125
#define BORDER_HEIGHT 60

#define START_SCORE 0
#define INCREMENT_SCORE 1

#define START_LIVES 3
#define MIN_LIVES 0

#define SETTING_WORM_SPEED_MIN 1
#define SETTING_WORM_SPEED_MAX 5
#define SETTING_APPLE_COUNT_MIN 1
#define SETTING_APPLE_COUNT_MAX 8
#define SETTING_SONG_COUNT 5

#define CHART_ANIM_INTERVAL_MS 110
#define CHART_WORM_STEP_PX 3
#define CHART_WORM_SEGMENTS 7
#define CHART_WORM_SEGMENT_GAP 5
#define CHART_WORM_Y 24
#define CHART_WORM_HEAD_RADIUS 3
#define CHART_STAR_COUNT 10

#define SETTING_MAGIC 0x574F524D /* WORM */
#define SCORE_MAGIC 0x53434F52   /* SCOR */

#endif
